"""add_role_name_to_candidate

Revision ID: 4734520fc8f4
Revises: 1dfa96dbbe22
Create Date: 2026-03-02 22:46:06.967116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4734520fc8f4'
down_revision: Union[str, Sequence[str], None] = '1dfa96dbbe22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
