"""Add session_question_id to CodeSubmission

Revision ID: 4792d27a8951
Revises: 4e8141f6c894
Create Date: 2026-03-06 01:08:33.364614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4792d27a8951'
down_revision: Union[str, Sequence[str], None] = '4e8141f6c894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_submissions', sa.Column('session_question_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'code_submissions', 'interview_session_questions', ['session_question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'code_submissions', type_='foreignkey')
    op.drop_column('code_submissions', 'session_question_id')
    # ### end Alembic commands ###
