"""Add InterviewSessionSection model and relations

Revision ID: 4e8141f6c894
Revises: d4e5f6a7b8c9
Create Date: 2026-03-06 00:51:28.090982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8141f6c894'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_session_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_session_id', sa.Uuid(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("section_type IN ('technical', 'coding', 'conversational')", name='check_section_type'),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed')", name='check_section_status'),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_session_sections_interview_session_id'), 'interview_session_sections', ['interview_session_id'], unique=False)
    # Clear existing data to avoid NOT NULL constraint violations
    op.execute("DELETE FROM interview_session_questions;")
    op.execute("DELETE FROM interview_sessions;")

    op.add_column('interview_session_questions', sa.Column('interview_session_id', sa.Uuid(), nullable=False))
    op.add_column('interview_session_questions', sa.Column('section_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_interview_session_questions_interview_id'), table_name='interview_session_questions')
    op.create_index(op.f('ix_interview_session_questions_interview_session_id'), 'interview_session_questions', ['interview_session_id'], unique=False)
    op.create_index(op.f('ix_interview_session_questions_section_id'), 'interview_session_questions', ['section_id'], unique=False)
    op.create_index('idx_session_section_order', 'interview_session_questions', ['interview_session_id', 'section_id', 'order'], unique=False)
    op.drop_constraint(op.f('interview_session_questions_interview_id_fkey'), 'interview_session_questions', type_='foreignkey')
    op.create_foreign_key(None, 'interview_session_questions', 'interview_session_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interview_session_questions', 'interview_sessions', ['interview_session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('interview_session_questions', 'interview_id')
    op.add_column('interview_sessions', sa.Column('current_section_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'interview_sessions', 'interview_session_sections', ['current_section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.drop_column('interview_sessions', 'current_section_id')
    op.add_column('interview_session_questions', sa.Column('interview_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'interview_session_questions', type_='foreignkey')
    op.drop_constraint(None, 'interview_session_questions', type_='foreignkey')
    op.create_foreign_key(op.f('interview_session_questions_interview_id_fkey'), 'interview_session_questions', 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_session_section_order', table_name='interview_session_questions')
    op.drop_index(op.f('ix_interview_session_questions_section_id'), table_name='interview_session_questions')
    op.drop_index(op.f('ix_interview_session_questions_interview_session_id'), table_name='interview_session_questions')
    op.create_index(op.f('ix_interview_session_questions_interview_id'), 'interview_session_questions', ['interview_id'], unique=False)
    op.drop_column('interview_session_questions', 'section_id')
    op.drop_column('interview_session_questions', 'interview_session_id')
    op.drop_index(op.f('ix_interview_session_sections_interview_session_id'), table_name='interview_session_sections')
    op.drop_table('interview_session_sections')
    # ### end Alembic commands ###
