"""create_interview_session_questions

Revision ID: 512b7bf918c5
Revises: 5e59a010ec1e
Create Date: 2026-03-02 21:33:54.256306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '512b7bf918c5'
down_revision: Union[str, Sequence[str], None] = '5e59a010ec1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use PostgreSQL DO block to check if table exists and create/modify accordingly
    op.execute(text("""
        DO $$ 
        BEGIN
            -- Create interview_session_questions table if it doesn't exist
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_name = 'interview_session_questions'
            ) THEN
                CREATE TABLE interview_session_questions (
                    id UUID PRIMARY KEY,
                    interview_id UUID NOT NULL,
                    question_id UUID,
                    custom_text TEXT,
                    "order" INTEGER NOT NULL DEFAULT 0,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
                    CONSTRAINT fk_interview_session_questions_interview_id 
                        FOREIGN KEY (interview_id) REFERENCES interviews(id) ON DELETE CASCADE,
                    CONSTRAINT fk_interview_session_questions_question_id 
                        FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE SET NULL,
                    CONSTRAINT check_question_or_custom_text 
                        CHECK ((question_id IS NOT NULL) OR (custom_text IS NOT NULL))
                );
                CREATE INDEX ix_interview_session_questions_interview_id 
                    ON interview_session_questions(interview_id);
            ELSE
                -- Table exists, modify it
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'interview_session_questions' AND column_name = 'custom_text'
                ) THEN
                    ALTER TABLE interview_session_questions ADD COLUMN custom_text TEXT;
                END IF;
                
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'interview_session_questions' AND column_name = 'question_text'
                ) THEN
                    ALTER TABLE interview_session_questions DROP COLUMN question_text;
                END IF;
                
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'interview_session_questions' AND column_name = 'time_limit_sec'
                ) THEN
                    ALTER TABLE interview_session_questions DROP COLUMN time_limit_sec;
                END IF;
            END IF;
            
            -- Drop columns from interview_templates if they exist
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'interview_templates' AND column_name = 'category_filters'
            ) THEN
                ALTER TABLE interview_templates DROP COLUMN category_filters;
            END IF;
            
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'interview_templates' AND column_name = 'total_questions'
            ) THEN
                ALTER TABLE interview_templates DROP COLUMN total_questions;
            END IF;
            
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'interview_templates' AND column_name = 'difficulty_distribution'
            ) THEN
                ALTER TABLE interview_templates DROP COLUMN difficulty_distribution;
            END IF;
        END $$;
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_templates', sa.Column('difficulty_distribution', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interview_templates', sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('interview_templates', sa.Column('category_filters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interview_session_questions', sa.Column('time_limit_sec', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('interview_session_questions', sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('interview_session_questions', 'custom_text')
    # ### end Alembic commands ###
