"""Add distinct configs to templates

Revision ID: ebfb639c6ea6
Revises: b8f4adf72de3
Create Date: 2026-03-05 21:08:08.498841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfb639c6ea6'
down_revision: Union[str, Sequence[str], None] = 'b8f4adf72de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_session_questions_session_id'), table_name='interview_session_questions')
    op.drop_constraint(op.f('interview_session_questions_session_id_fkey'), 'interview_session_questions', type_='foreignkey')
    op.drop_column('interview_session_questions', 'answered')
    op.drop_column('interview_session_questions', 'session_id')
    op.add_column('interview_templates', sa.Column('technical_config', sa.JSON(), nullable=True))
    op.add_column('interview_templates', sa.Column('coding_config', sa.JSON(), nullable=True))
    op.add_column('interview_templates', sa.Column('conversational_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_templates', 'conversational_config')
    op.drop_column('interview_templates', 'coding_config')
    op.drop_column('interview_templates', 'technical_config')
    op.add_column('interview_session_questions', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('interview_session_questions', sa.Column('answered', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('interview_session_questions_session_id_fkey'), 'interview_session_questions', 'interview_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_interview_session_questions_session_id'), 'interview_session_questions', ['session_id'], unique=False)
    # ### end Alembic commands ###
