"""
Interview Router — Admin-only scheduling endpoints (Refactored for SQLAlchemy)
----------------------------------------------------
POST   /admin/interviews/schedule          – Create a new scheduled interview
PUT    /admin/interviews/{id}/reschedule   – Move interview to a new datetime
PUT    /admin/interviews/{id}/cancel       – Cancel a non-completed interview
"""

import uuid
from fastapi import APIRouter, Depends, status, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List

from sqlalchemy import select, func
from app.db.sql.models.interview_template import InterviewTemplate
from app.db.sql.models.coding_problem import CodingProblem
from app.db.sql.models.question import Question

from app.api.v1.auth_router import get_current_admin
from app.db.sql.session import get_db_session
from app.db.sql.models.user import User
from app.schemas.interview import (
    ScheduleInterviewRequest,
    ScheduleInterviewResponse,
    RescheduleInterviewRequest,
    RescheduleInterviewResponse,
    CancelInterviewRequest,
    CancelInterviewResponse,
)
from app.schemas.interview_template import TemplatePreviewResponse
from app.services.interview_admin_sql_service import InterviewAdminSQLService
from app.services.template_engine import template_engine
from app.db.sql.enums import InterviewStatus

router = APIRouter()

def validate_uuid(id_str: str) -> uuid.UUID:
    try:
        return uuid.UUID(id_str)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Invalid UUID: {id_str}",
        )

@router.get(
    "/templates",
    summary="List active interview templates",
    description="Admin-only. Returns all interview templates with is_active=True.",
)
async def list_templates(
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    return await InterviewAdminSQLService.list_active_templates(session)


@router.post(
    "/templates/{template_id}/preview",
    response_model=TemplatePreviewResponse,
    summary="Preview questions generated by a template",
    description="Admin-only. Generates but does not persist questions.",
)
async def preview_template(
    template_id: str,
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    validated_id = validate_uuid(template_id)
    template = await session.get(InterviewTemplate, validated_id)
    if not template:
        raise HTTPException(status_code=404, detail="Template not found")

    # 1. Technical Preview — always use technical_config; fall back to legacy settings
    technical_questions_res = []
    distribution = None
    if template.technical_config and isinstance(template.technical_config, dict):
        # Support both flat map {"easy": 2} and nested {"difficulty_distribution": {"easy": 2}}
        if any(k.lower() in ["easy", "medium", "hard"] for k in template.technical_config.keys()):
            distribution = template.technical_config
        else:
            distribution = template.technical_config.get("difficulty_distribution")

    if not distribution and template.settings and isinstance(template.settings, dict):
        distribution = template.settings.get("difficulty_distribution")

    if distribution and isinstance(distribution, dict):
        from app.db.sql.models.question import DifficultyEnum
        for diff_str, count in distribution.items():
            if not isinstance(count, int) or count <= 0:
                continue
            
            try:
                # Resolve enum in Python to avoid database-side cast issues with native enums
                target_diff = DifficultyEnum(diff_str.upper())
                
                query = select(Question).where(
                    Question.difficulty == target_diff,
                    Question.is_active == True
                ).order_by(func.random()).limit(count)
                
                res = await session.execute(query)
                technical_questions_res.extend(res.scalars().all())
            except (ValueError, Exception) as e:
                # If one difficulty fails (e.g. invalid key or DB error), 
                # we log and continue to next section without crashing the whole preview.
                # However, if it's a DB error, the transaction might be failed.
                # We're in a simple GET, so we just log.
                import logging
                logging.getLogger(__name__).warning(f"Technical preview loop error for {diff_str}: {e}")
                continue

    technical_preview = [
        {
            "question_id": q.id,
            "text": q.text,
            "difficulty": q.difficulty,
            "category": q.category,
        }
        for q in technical_questions_res
    ]

    # 2. Coding Preview
    coding_preview = []
    coding_config = template.coding_config or {}
    if isinstance(coding_config, dict):
        count = coding_config.get("count", 0)
        difficulties = coding_config.get("difficulty", [])
        
        if isinstance(count, int) and count > 0 and isinstance(difficulties, list) and difficulties:
            # Normalize difficulties to uppercase for comparison
            valid_diffs = [d.upper() for d in difficulties if isinstance(d, str)]
            
            if valid_diffs:
                try:
                    query = select(CodingProblem).where(
                        func.upper(CodingProblem.difficulty).in_(valid_diffs)
                    ).order_by(func.random()).limit(count)
                    
                    res = await session.execute(query)
                    problems = res.scalars().all()
                    coding_preview = [
                        {
                            "problem_id": p.id,
                            "title": p.title,
                            "difficulty": p.difficulty
                        } for p in problems
                    ]
                except Exception as e:
                    import logging
                    logging.getLogger(__name__).warning(f"Coding preview error: {e}")

    # 3. Conversational Preview
    conv_config = template.conversational_config or {}
    rounds = conv_config.get("rounds", 0) if isinstance(conv_config, dict) else 0

    conversational_preview = {
        "rounds": rounds if isinstance(rounds, int) else 0,
        "description": "Conversational interview powered by LLM"
    }

    return {
        "technical_section": {"questions": technical_preview},
        "coding_section": {"problems": coding_preview},
        "conversational_section": conversational_preview
    }


@router.get(
    "/summary",
    summary="Get a lightweight summary of all interviews",
    description=(
        "Admin-only. Returns candidate_id, interview_id, status, and scheduled_at "
        "for every interview. Excludes curated_questions for performance."
    ),
)
async def get_interview_summary(
    limit: int = 10,
    offset: int = 0,
    search: str = "",
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    result = await InterviewAdminSQLService.get_interview_summary(session, limit, offset, search)
    data = [
        {
            "interview_id": str(s["interview_id"]),
            "candidate_id": str(s["candidate_id"]) if s["candidate_id"] else None,
            "status": s["status"].value if isinstance(s["status"], InterviewStatus) else s["status"],
            "scheduled_at": s["scheduled_at"],
            "overall_score": s.get("overall_score"),
        }
        for s in result["data"]
    ]
    return {
        "data": data,
        "total": result["total"],
        "limit": limit,
        "offset": offset
    }


@router.post(
    "/schedule",
    response_model=ScheduleInterviewResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Schedule a new interview for a candidate",
    description=(
        "Admin-only. Validates candidate eligibility, checks for existing "
        "active interviews, verifies template, and creates the interview document "
        "with a mock curated questions payload."
    ),
)
async def schedule_interview(
    request: ScheduleInterviewRequest,
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    template_id = validate_uuid(request.template_id)
    candidate_id = validate_uuid(request.candidate_id)
    
    interview = await InterviewAdminSQLService.create_interview(
        session=session,
        template_id=template_id,
        candidate_id=candidate_id,
        assigned_by=current_admin.id,
        scheduled_at=request.scheduled_at,
        questions=request.questions,
    )
    
    return {
        "id": str(interview.id),
        "candidate_id": str(interview.candidate_id),
        "template_id": str(interview.template_id),
        "assigned_by": str(interview.assigned_by),
        "status": interview.status.value if isinstance(interview.status, InterviewStatus) else interview.status,
        "scheduled_at": interview.scheduled_at,
        "curated_questions": interview.curated_questions,
        "created_at": interview.created_at,
    }

@router.put(
    "/{interview_id}/reschedule",
    response_model=RescheduleInterviewResponse,
    status_code=status.HTTP_200_OK,
    summary="Reschedule an existing interview",
    description=(
        "Admin-only. Moves a 'scheduled' interview to a new future datetime. "
        "Returns 409 if status is anything other than 'scheduled'."
    ),
)
async def reschedule_interview(
    interview_id: str,
    request: RescheduleInterviewRequest,
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    validated_id = validate_uuid(interview_id)
    interview = await InterviewAdminSQLService.reschedule_interview(
        session=session,
        interview_id=validated_id,
        scheduled_at=request.scheduled_at,
    )
    
    return {
        "id": str(interview.id),
        "status": interview.status.value if isinstance(interview.status, InterviewStatus) else interview.status,
        "scheduled_at": interview.scheduled_at,
        "updated_at": interview.updated_at,
    }


@router.put(
    "/{interview_id}/cancel",
    response_model=CancelInterviewResponse,
    status_code=status.HTTP_200_OK,
    summary="Cancel an interview",
    description=(
        "Admin-only. Cancels an interview by setting status to 'cancelled'. "
        "The document is never deleted. Returns 409 if status is 'completed'."
    ),
)
async def cancel_interview(
    interview_id: str,
    request: CancelInterviewRequest = CancelInterviewRequest(),
    current_admin: User = Depends(get_current_admin),
    session: AsyncSession = Depends(get_db_session),
):
    validated_id = validate_uuid(interview_id)
    interview = await InterviewAdminSQLService.cancel_interview(
        session=session,
        interview_id=validated_id,
        reason=request.reason,
    )
    
    return {
        "id": str(interview.id),
        "status": interview.status.value if isinstance(interview.status, InterviewStatus) else interview.status,
        "cancelled_at": interview.cancelled_at,
        "reason": interview.cancellation_reason,
    }
